"""Generate the entity gazetteer the session layer matches questions against.

    python scripts/build_gazetteer.py

Deciding whether "Show AR_NPD_Shirting items" changes the subject requires
knowing which strings name a subject. Hardcoding them would not survive a
schema change, so they are read from the database instead: any column listed
in GAZETTEER_COLUMNS whose distinct values are few enough to be identifiers
rather than free text.

Writes metadata/entity_gazetteer.yaml. Re-run after the data changes.
"""

from __future__ import annotations

from pathlib import Path

import _bootstrap  # noqa: F401
import yaml

from config.logging import register_secrets
from config.settings import load_settings
from database.connection import run_readonly

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "metadata" / "entity_gazetteer.yaml"

# (table, column, role). "entity" values name the subject of a question and so
# can end a conversational block; "dimension" values only ever narrow it.
GAZETTEER_COLUMNS = [
    ("tms_business_object_flat", "business_object_type", "entity"),
    ("tms_business_object_flat", "business_unit", "dimension"),
    ("tms_business_object_flat", "business_object_status", "dimension"),
    ("tms_business_object_flat", "business_object_color", "dimension"),
    ("tms_task_flat", "task_status", "dimension"),
    ("tms_task_flat", "task_sla_status", "dimension"),
]

# Above this a column is free text, not a set of identifiers.
MAX_DISTINCT = 60


def main() -> int:
    settings = load_settings()
    register_secrets(settings.secrets())

    doc: dict[str, dict] = {"entity": {}, "dimension": {}}
    for table, column, role in GAZETTEER_COLUMNS:
        sql = (
            f'SELECT DISTINCT "{column}" FROM {table} '
            f'WHERE "{column}" IS NOT NULL AND "{column}" <> \'\' '
            f'ORDER BY 1'
        )
        result = run_readonly(settings, sql, settings.statement_timeout_ms)
        if result.error:
            print(f"  skip {table}.{column}: {result.error.splitlines()[0]}")
            continue
        values = [str(r[0]) for r in result.rows]
        if len(values) > MAX_DISTINCT:
            print(f"  skip {table}.{column}: {len(values)} distinct (free text)")
            continue
        doc[role].setdefault(f"{table}.{column}", values)
        print(f"  {role:<9} {table}.{column}: {len(values)} value(s)")

    OUT.write_text(
        "# Generated by scripts/build_gazetteer.py -- do not edit by hand.\n"
        "#\n"
        "# 'entity' values name the subject of a question; naming a different one\n"
        "# ends the current conversational block. 'dimension' values only narrow\n"
        "# the current subject and never reset it.\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    n_entity = sum(len(v) for v in doc["entity"].values())
    n_dim = sum(len(v) for v in doc["dimension"].values())
    print(f"\nwrote {OUT.relative_to(ROOT)}: {n_entity} entity value(s), {n_dim} dimension value(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
